### PR TITLE
Bump to .NET 6.0.100-alpha.1.20562.2

### PR DESCRIPTION
**Pull request by jonathanpeppers**
* Everything is `net6.0` now
* Android 11.0.100.239
* iOS 14.2.100.27
* `$(_DotNetPackageVersion)` can use 5.0.0 stable NuGet packages

### CODE REVIEW

**Comment by jonathanpeppers** [comment]
@rolfbjarne the issue I'm seeing now is `mlaunch` seems like it is missing?

I don't have `/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/14.2.100-ci.main.27/tools/bin/mlaunch`

And I get this from`-t:Run`:

```
"HelloiOS/HelloiOS.csproj" (Run target) (1:7) ->
    (_PrepareRunMobile target) -> 
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/14.2.100-ci.main.27/targets/Xamarin.Shared.Sdk.targets(663,3): error MSB4018: The "GetMlaunchArguments" task failed unexpectedly. [HelloiOS/HelloiOS.csproj]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/14.2.100-ci.main.27/targets/Xamarin.Shared.Sdk.targets(663,3): error MSB4018: System.AggregateException: One or more errors occurred. (No such file or directory) [HelloiOS/HelloiOS.csproj]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/14.2.100-ci.main.27/targets/Xamarin.Shared.Sdk.targets(663,3): error MSB4018:  ---> System.ComponentModel.Win32Exception (2): No such file or directory [HelloiOS/HelloiOS.csproj]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/14.2.100-ci.main.27/targets/Xamarin.Shared.Sdk.targets(663,3): error MSB4018:    at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec) [HelloiOS/HelloiOS.csproj]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/14.2.100-ci.main.27/targets/Xamarin.Shared.Sdk.targets(663,3): error MSB4018:    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) [HelloiOS/HelloiOS.csproj]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/14.2.100-ci.main.27/targets/Xamarin.Shared.Sdk.targets(663,3): error MSB4018:    at System.Diagnostics.Process.Start() [HelloiOS/HelloiOS.csproj]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/14.2.100-ci.main.27/targets/Xamarin.Shared.Sdk.targets(663,3): error MSB4018:    at Xamarin.Utils.Execution.<>c__DisplayClass24_1.<RunAsync>b__0() in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/common/Execution.cs:line 103 [HelloiOS/HelloiOS.csproj]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/14.2.100-ci.main.27/targets/Xamarin.Shared.Sdk.targets(663,3): error MSB4018: --- End of stack trace from previous location --- [HelloiOS/HelloiOS.csproj]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/14.2.100-ci.main.27/targets/Xamarin.Shared.Sdk.targets(663,3): error MSB4018:    at Xamarin.MacDev.Tasks.XamarinTask.ExecuteAsync(String fileName, IList`1 arguments, String sdkDevPath, Dictionary`2 environment, Boolean mergeOutput, Boolean showErrorIfFailure) in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/msbuild/Xamarin.MacDev.Tasks.Core/Tasks/XamarinTask.cs:line 103 [HelloiOS/HelloiOS.csproj]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/14.2.100-ci.main.27/targets/Xamarin.Shared.Sdk.targets(663,3): error MSB4018:    --- End of inner exception stack trace --- [HelloiOS/HelloiOS.csproj]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/14.2.100-ci.main.27/targets/Xamarin.Shared.Sdk.targets(663,3): error MSB4018:    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) [HelloiOS/HelloiOS.csproj]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/14.2.100-ci.main.27/targets/Xamarin.Shared.Sdk.targets(663,3): error MSB4018:    at System.Threading.Tasks.Task`1.get_Result() [HelloiOS/HelloiOS.csproj]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/14.2.100-ci.main.27/targets/Xamarin.Shared.Sdk.targets(663,3): error MSB4018:    at Xamarin.iOS.Tasks.GetMlaunchArgumentsTaskBase.GetDeviceTypes() in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/msbuild/Xamarin.iOS.Tasks.Core/Tasks/GetMlaunchArgumentsTaskBase.cs:line 66 [HelloiOS/HelloiOS.csproj]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/14.2.100-ci.main.27/targets/Xamarin.Shared.Sdk.targets(663,3): error MSB4018:    at Xamarin.iOS.Tasks.GetMlaunchArgumentsTaskBase.GenerateCommandLineCommands() in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/msbuild/Xamarin.iOS.Tasks.Core/Tasks/GetMlaunchArgumentsTaskBase.cs:line 128 [HelloiOS/HelloiOS.csproj]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/14.2.100-ci.main.27/targets/Xamarin.Shared.Sdk.targets(663,3): error MSB4018:    at Xamarin.iOS.Tasks.GetMlaunchArgumentsTaskBase.Execute() in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/msbuild/Xamarin.iOS.Tasks.Core/Tasks/GetMlaunchArgumentsTaskBase.cs:line 199 [HelloiOS/HelloiOS.csproj]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/14.2.100-ci.main.27/targets/Xamarin.Shared.Sdk.targets(663,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [HelloiOS/HelloiOS.csproj]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/14.2.100-ci.main.27/targets/Xamarin.Shared.Sdk.targets(663,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [HelloiOS/HelloiOS.csproj]
```

**Comment by rolfbjarne** [comment]
@jonathanpeppers I found the problem, and I've created a PR with the fix (https://github.com/xamarin/xamarin-macios/pull/10122)

**Comment by jonathanpeppers** [comment]
Thanks @rolfbjarne the latest build seems to work!

**Review by pjcollins — APPROVED** [review]

**Comment by lambdageek** [comment]
@jonathanpeppers Hi, I tried out the steps in the readme (downloaded the linked mac dotnet 6 preview .pkg, and the ios workload bundle) and ran ```dotnet build``` for the HelloiOS sample.  I got:
```
/usr/local/share/dotnet/sdk/6.0.100-preview.1.21081.5/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(109,5): error NETSDK1139: The target platform identifier ios was not recognized. [/Users/alklig/work/net6-mobile-samples/HelloiOS/HelloiOS.csproj]
```

I had to manually 
```
sudo touch /usr/local/share/dotnet/sdk/6.0.100-preview.1.21081.5/EnableWorkloadResolver.sentinel
```

and then 
```
dotnet build
```
worked.

**Comment by jonathanpeppers** [comment]
@lambdageek only the Android `.pkg` and `.msi` create the `.sentinel` file right now.

Really, I would rather we get rid of the file completely...

**Pull request merged**
