### PR TITLE
Bump iOS to get fix for #35.

### PR DESCRIPTION
**Pull request by rolfbjarne**
Fixes https://github.com/xamarin/net6-samples/issues/35.

### CODE REVIEW

**Comment by rolfbjarne** [comment]
@jonathanpeppers xcode provisioning failed with:

> ##[error]Unable to determine the domain name

which doesn't make much sense?

**Comment by jonathanpeppers** [comment]
This is the same error I got when I was provisioning Xcode and didn't have the right variable groups.

@pjcollins do you know if something changed with these since last week?

https://github.com/xamarin/net6-samples/blob/5c9a7dfe46505676ab0f9be666cbd2be1f58ab0d/azure-pipelines.yml#L55-L56

**Comment by pjcollins** [comment]
The "secret download" steps were skipped:
> References service endpoint. PRs from repository forks are not allowed to access secrets in the pipeline. For more information see https://go.microsoft.com/fwlink/?linkid=862029

I'll update the build definition to allow this for org members.

**Review by jonathanpeppers — APPROVED** [review]

**Pull request merged**
